language: cpp

sudo: false

compiler:
    #- gcc
    - clang

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make && ./test/tests

os:
    #- linux
    - osx

env:
  global:
  - LANG="en_US.UTF-8"
